# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Briefkit < Formula
  desc "Local orchestration tool for subscription-based coding CLIs"
  homepage "https://github.com/orbiqd/orbiqd-briefkit"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orbiqd/orbiqd-briefkit/releases/download/v0.4.0/briefkit_0.4.0_darwin_amd64.zip"
      sha256 "8636257aa0e406f5621d832bae13a7d1fdc497a9de6748d84511f58bee249e55"

      def install
        bin.install "briefkit-ctl"
        bin.install "briefkit-mcp"
        bin.install "briefkit-runner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orbiqd/orbiqd-briefkit/releases/download/v0.4.0/briefkit_0.4.0_darwin_arm64.zip"
      sha256 "52a861f3cca3f92d4f47a3c98de002e66c3dccd440be0f12d4fb41c2fc184cb7"

      def install
        bin.install "briefkit-ctl"
        bin.install "briefkit-mcp"
        bin.install "briefkit-runner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orbiqd/orbiqd-briefkit/releases/download/v0.4.0/briefkit_0.4.0_linux_amd64.tar.gz"
      sha256 "c3fae73bce2f7b76dfa1b318b00bae480db771dbee138ed87241ea58f9f7d450"
      def install
        bin.install "briefkit-ctl"
        bin.install "briefkit-mcp"
        bin.install "briefkit-runner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orbiqd/orbiqd-briefkit/releases/download/v0.4.0/briefkit_0.4.0_linux_arm64.tar.gz"
      sha256 "2a9761758a79415a6538ba858488ddbab6939b3d955a55a64eeb2c9c05023733"
      def install
        bin.install "briefkit-ctl"
        bin.install "briefkit-mcp"
        bin.install "briefkit-runner"
      end
    end
  end

  test do
    system "#{bin}/briefkit-ctl", "--version"
  end
end
