# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Briefkit < Formula
  desc "Local orchestration tool for subscription-based coding CLIs"
  homepage "https://github.com/orbiqd/orbiqd-briefkit"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orbiqd/orbiqd-briefkit/releases/download/v0.8.0/briefkit_0.8.0_darwin_amd64.zip"
      sha256 "947d7184082fe690907c5086e659e016d2d80fbe4e4dd915a1f405bed797af82"

      define_method(:install) do
        bin.install "briefkit-ctl"
        bin.install "briefkit-mcp"
        bin.install "briefkit-runner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orbiqd/orbiqd-briefkit/releases/download/v0.8.0/briefkit_0.8.0_darwin_arm64.zip"
      sha256 "2b665cc6a10e9fde70a2b56305101d1d1a2119206689842287b6a6ce1c68150c"

      define_method(:install) do
        bin.install "briefkit-ctl"
        bin.install "briefkit-mcp"
        bin.install "briefkit-runner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orbiqd/orbiqd-briefkit/releases/download/v0.8.0/briefkit_0.8.0_linux_amd64.tar.gz"
      sha256 "091bff7c6180b0ea63e266042fd7bcb459bc2e977c7af50e34881ae6d53ebf44"
      define_method(:install) do
        bin.install "briefkit-ctl"
        bin.install "briefkit-mcp"
        bin.install "briefkit-runner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orbiqd/orbiqd-briefkit/releases/download/v0.8.0/briefkit_0.8.0_linux_arm64.tar.gz"
      sha256 "76d70e15572aa412bf5eb6783896a1f76aba1a4817aabc98c6bec7b202bcea7f"
      define_method(:install) do
        bin.install "briefkit-ctl"
        bin.install "briefkit-mcp"
        bin.install "briefkit-runner"
      end
    end
  end

  test do
    system "#{bin}/briefkit-ctl", "--version"
  end
end
