# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Briefkit < Formula
  desc "Local orchestration tool for subscription-based coding CLIs"
  homepage "https://github.com/orbiqd/orbiqd-briefkit"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orbiqd/orbiqd-briefkit/releases/download/v0.6.0/briefkit_0.6.0_darwin_amd64.zip"
      sha256 "f62dac688efb26aedcf19c1268e6ca281002f326754dcc644e71271661825566"

      define_method(:install) do
        bin.install "briefkit-ctl"
        bin.install "briefkit-mcp"
        bin.install "briefkit-runner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orbiqd/orbiqd-briefkit/releases/download/v0.6.0/briefkit_0.6.0_darwin_arm64.zip"
      sha256 "64a3cbe6bb9d720441e5b25a447be58330e69d687418bdf3e3d51349d00f0c0f"

      define_method(:install) do
        bin.install "briefkit-ctl"
        bin.install "briefkit-mcp"
        bin.install "briefkit-runner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orbiqd/orbiqd-briefkit/releases/download/v0.6.0/briefkit_0.6.0_linux_amd64.tar.gz"
      sha256 "7d3d7f4abd53f7d23cecf7335856f35c6a187f481c161e61f7b659b74f988356"
      define_method(:install) do
        bin.install "briefkit-ctl"
        bin.install "briefkit-mcp"
        bin.install "briefkit-runner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orbiqd/orbiqd-briefkit/releases/download/v0.6.0/briefkit_0.6.0_linux_arm64.tar.gz"
      sha256 "dd9cab7153fdf0c311885e0b0ba27ad1bd4aac56a98bdfe3908a43835edef3b8"
      define_method(:install) do
        bin.install "briefkit-ctl"
        bin.install "briefkit-mcp"
        bin.install "briefkit-runner"
      end
    end
  end

  test do
    system "#{bin}/briefkit-ctl", "--version"
  end
end
